# Generated by Django 5.0.6 on 2024-06-17 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecfood_admin', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=True),
        ),
    ]
