# Generated by Django 5.0.6 on 2024-06-25 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tecfood_cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartdish',
            old_name='cart_id',
            new_name='cart',
        ),
        migrations.RenameField(
            model_name='orderdish',
            old_name='user_id',
            new_name='user',
        ),
    ]
