# Generated by Django 5.0.6 on 2024-06-25 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tecfood_cart', '0003_rename_dish_id_cartdish_dish_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartdish',
            old_name='cart',
            new_name='cart_id',
        ),
    ]
