# Generated by Django 5.0.6 on 2024-06-25 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecfood_cart', '0004_rename_cart_cartdish_cart_id'),
        ('tecfood_dish', '0002_remove_dish_ima_url_dish_img_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDishItem',
            fields=[
                ('order_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dish_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tecfood_dish.dish')),
                ('order_dish_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tecfood_cart.orderdish')),
            ],
            options={
                'db_table': 'order_dish_item',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('CREDIT_CARD', 'Credit Card'), ('DEBIT_CARD', 'Debit Card'), ('PAYPAL', 'PayPal')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('FAILED', 'Failed'), ('COMPLETED', 'Completed')], default='PENDING', max_length=10)),
                ('order_dish_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tecfood_cart.orderdish')),
            ],
            options={
                'db_table': 'payment',
            },
        ),
    ]
