# Generated by Django 5.0.6 on 2024-06-25 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tecfood_cart', '0006_rename_order_dish_id_payment_order_dish'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdishitem',
            old_name='dish_id',
            new_name='dish',
        ),
        migrations.RenameField(
            model_name='orderdishitem',
            old_name='order_dish_id',
            new_name='order_dish',
        ),
    ]
