# Generated by Django 5.0.6 on 2024-06-30 19:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecfood_cart', '0007_rename_dish_id_orderdishitem_dish_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('CARD', 'Card'), ('PAYPAL', 'PayPal')], max_length=6),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('FAILED', 'Failed'), ('COMPLETED', 'Completed')], default='PENDING', max_length=9),
        ),
    ]
