# Generated by Django 5.0.6 on 2024-07-01 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecfood_cart', '0008_payment_created_at_alter_payment_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
