# Generated by Django 5.0.6 on 2024-07-01 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecfood_cart', '0009_alter_payment_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('CARD', 'Card'), ('PAYPAL', 'PayPal')], max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('FAILED', 'Failed'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20),
        ),
    ]
