# Generated by Django 5.0.6 on 2024-06-21 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecfood_dish', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='ima_url',
        ),
        migrations.AddField(
            model_name='dish',
            name='img_url',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
