# Generated by Django 5.0.6 on 2024-06-25 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tecfood_dish', '0002_remove_dish_ima_url_dish_img_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dish',
            old_name='dish_category_id',
            new_name='dish_category',
        ),
    ]
